### ISSUE TITLE
从 官网下载 ideaIU-2017.3.2.win 解压版安装插件后不能自动生成set方法

### ISSUE THREAD

**Issue by zhangleijie** [donnie0915/GenerateAllSetter#1]
楼主 我安装了你的插件，但是生成set方法时报错、 这是什么原因那？ 我用的jdk1.8 从idea官网下载最新版解压版的idea。

**Comment by zhangleijie** [comment]
@donnie0915  你邮箱地址是 我把错误信息发你。

**Comment by donnie0915** [comment]
hjp22222@163.com 发过来看看，最新版都我还没试过。

**Comment by zhangleijie** [comment]
@donnie0915  发你邮箱了

**Comment by zhangleijie** [comment]
![error set method](https://user-images.githubusercontent.com/10412168/35202213-4d914f28-ff5c-11e7-8d5b-b2d813240eb6.png)
@donnie0915 
![set method](https://user-images.githubusercontent.com/10412168/35202211-47a2d7c6-ff5c-11e7-8ff0-5756662a964e.png)

**Comment by zhangleijie** [comment]
在最新版本上， 我的可以生成了。

**Comment by chf-gh** [comment]
> ![error set method](https://user-images.githubusercontent.com/10412168/35202213-4d914f28-ff5c-11e7-8d5b-b2d813240eb6.png)
> @donnie0915
> ![set method](https://user-images.githubusercontent.com/10412168/35202211-47a2d7c6-ff5c-11e7-8ff0-5756662a964e.png)

遇到同样的问题，请问你怎么解决的？
